package com.swms.common.utils.exception.code_enum;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum UserErrorDescEnum implements IBaseError {

    USER_ERROR_DESC_ENUM("USE001001", "user base error"),
    ERR_EMPTY_OLD_CRED("USE001003", "ERR_EMPTY_OLD_PASSWORD"),
    ERR_EMPTY_NEW_CRED("USE001004", "ERR_EMPTY_NEW_PASSWORD"),
    ERR_CRED_TOO_SHORT("USE001005", "ERR_PASSWORD_TOO_SHORT"),
    NO_AUTHED_USER_FOUND("USE001006", "NO_AUTHED_USER_FOUND"),
    ERROR_WRONG_OLD_CRED("USE001007", "ERROR_WRONG_OLD_PASSWORD"),
    ERR_AUTHED_CLIENT_ALREADY_EXISTS("USE001008", "ERR_AUTHED_CLIENT_ALREADY_EXISTS"),
    ERR_EMPTY_AUTH_TYPE("USE001009", "ERR_EMPTY_AUTH_TYPE"),
    ERR_CLIENT_DOES_NOT_EXIST("USE001010", "ERR_CLIENT_DOES_NOT_EXIST"),
    ERR_INIT_ENUM_MAP("USE001011", "ERR_INIT_ENUM_MAP"),
    ERR_EMPTY_STATUS("USE001012", "ERR_EMPTY_STATUS"),
    ERR_INCORRECT_STATUS("USE001013", "ERR_INCORRECT_STATUS"),
    ERR_ROLE_NOT_FOUND("USE001014", "ERR_ROLE_NOT_FOUND"),
    ERR_ROLE_ADMIN_IS_IMMUTABLE("USE001015", "ERR_ROLE_ADMIN_IS_IMMUTABLE"),
    ERR_ROLE_CODE_EXISTS("USE001016", "ERR_ROLE_CODE_EXISTS"),
    ERR_WRONG_CREDENTIALS("USE001017", "ERR_WRONG_CREDENTIALS"),
    ERR_EMPTY_USER_NAME("USE001018", "ERR_EMPTY_USER_NAME"),
    ERR_EMPTY_ROLE_ID_SET("USE001019", "ERR_EMPTY_ROLE_ID_SET"),
    ERR_USER_NAME_EXISTS("USE001020", "ERR_USER_NAME_EXISTS"),
    ERR_EMPTY_USERADD_PARAM("USE001021", "ERR_EMPTY_USERADD_PARAM"),
    ERR_EMPTY_USER_ID("USE001022", "ERR_EMPTY_USER_ID"),
    ERR_EMPTY_ROLE_ID("USE001023", "ERR_EMPTY_ROLE_ID"),
    ERR_ROLE_IS_DISABLE("USE001024", "ERR_ROLE_IS_DISABLE"),
    ERR_CRED_NOT_MATCHED("USE001025", "ERR_PASSWORD_NOT_MATCHED"),
    ERR_USER_IS_NOT_DISABLED("USE001026", "ERR_USER_IS_NOT_DISABLED"),
    ERR_USER_CAN_NOT_DISABLE_OR_DELETE_SELF("USE001027", "ERR_USER_CAN_NOT_DISABLE_OR_DELETE_SELF"),
    ERR_ROLE_IS_ENABLE_AND_USED("USE001028", "ERR_ROLE_IS_ENABLE_AND_USED"),
    ERR_INVALID_EXTERNAL_LOGIN("USE001029", "ERR_INVALID_EXTERNAL_LOGIN"),
    ERR_INVALID_LOGOUT_REDIRECT_URL("USE001030", "ERR_INVALID_LOGOUT_REDIRECT_URL");

    private final String code;
    private final String desc;
}
