spring:
  application:
    name: station
  profiles:
    active: prod
  cloud:
    nacos:
      config:
        server-addr: ${nacos.hairoutech.com:172.18.35.23}:${nacos.port:8181}
        prefix: ${spring.application.name}
        file-extension: yml
        namespace: station-server-dev
        group: swms
        username: nacos
        password: nacos
  config:
    import:
      - nacos:station-server-redisson.yml
