package com.swms.utils.exception.code_enum;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum UserErrorDescEnum implements IBaseError {

    USER_ERROR_DESC_ENUM("USE001001", "user base error"),
    ERR_EMPTY_OLD_CRED("USE001002", "ERR_EMPTY_OLD_PASSWORD"),
    ERR_EMPTY_NEW_CRED("USE001002", "ERR_EMPTY_NEW_PASSWORD"),
    ERR_CRED_TOO_SHORT("USE001002", "ERR_PASSWORD_TOO_SHORT"),
    NO_AUTHED_USER_FOUND("USE001002", "NO_AUTHED_USER_FOUND"),
    ERROR_WRONG_OLD_CRED("USE001002", "ERROR_WRONG_OLD_PASSWORD"),
    ERR_AUTHED_CLIENT_ALREADY_EXISTS("USE001002", "ERR_AUTHED_CLIENT_ALREADY_EXISTS"),
    ERR_EMPTY_AUTH_TYPE("USE001002", "ERR_EMPTY_AUTH_TYPE"),
    ERR_CLIENT_DOES_NOT_EXIST("USE001002", "ERR_CLIENT_DOES_NOT_EXIST"),
    ERR_INIT_ENUM_MAP("USE001002", "ERR_INIT_ENUM_MAP"),
    ERR_EMPTY_STATUS("USE001002", "ERR_EMPTY_STATUS"),
    ERR_INCORRECT_STATUS("USE001002", "ERR_INCORRECT_STATUS"),
    ERR_ROLE_NOT_FOUND("USE001002", "ERR_ROLE_NOT_FOUND"),
    ERR_ROLE_ADMIN_IS_IMMUTABLE("USE001002", "ERR_ROLE_ADMIN_IS_IMMUTABLE"),
    ERR_ROLE_CODE_EXISTS("USE001002", "ERR_ROLE_CODE_EXISTS"),
    ERR_WRONG_CREDENTIALS("USE001002", "ERR_WRONG_CREDENTIALS"),
    ERR_EMPTY_USER_NAME("USE001002", "ERR_EMPTY_USER_NAME"),
    ERR_EMPTY_ROLE_ID_SET("USE001002", "ERR_EMPTY_ROLE_ID_SET"),
    ERR_USER_NAME_EXISTS("USE001002", "ERR_USER_NAME_EXISTS"),
    ERR_EMPTY_USERADD_PARAM("USE001002", "ERR_EMPTY_USERADD_PARAM"),
    ERR_EMPTY_USER_ID("USE001002", "ERR_EMPTY_USER_ID"),
    ERR_EMPTY_ROLE_ID("USE001002", "ERR_EMPTY_ROLE_ID"),
    ERR_ROLE_IS_DISABLE("USE001002", "ERR_ROLE_IS_DISABLE"),
    ERR_CRED_NOT_MATCHED("USE001002", "ERR_PASSWORD_NOT_MATCHED"),
    ERR_USER_IS_NOT_DISABLED("USE001002", "ERR_USER_IS_NOT_DISABLED"),
    ERR_USER_CAN_NOT_DISABLE_OR_DELETE_SELF("USE001002", "ERR_USER_CAN_NOT_DISABLE_OR_DELETE_SELF"),
    ERR_ROLE_IS_ENABLE_AND_USED("USE001002", "ERR_ROLE_IS_ENABLE_AND_USED"),
    ERR_INVALID_EXTERNAL_LOGIN("USE001002", "ERR_INVALID_EXTERNAL_LOGIN"),
    ERR_INVALID_LOGOUT_REDIRECT_URL("USE001002", "ERR_INVALID_LOGOUT_REDIRECT_URL");

    private final String code;
    private final String desc;
}
